### ISSUE TITLE
Delete this repo? 

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/Semana_de_Asociaciones_2017#1]
Do not see contents... Past event...

**Comment by Siotma** [comment]
The key is that this repo has not been used for the purpose it was made. If we delete it, the next year, people in ASROB would like to know what was done this year, and they won't have any related information.

Would you prefer to use the ASROB drive for this purpose instead? The point is not to lose the information...

**Comment by jgvictores** [comment]
Oh, sorry, was seeing it via mobile interface and hadn't seen the files. Two options here:
- Move contents to https://github.com/asrob-uc3m/actas and delete.
- Rename to `semana-de-asociaciones-2017`... <- I'd be cool with this :-)

**Comment by Siotma** [comment]
As I see, it would be enough to use the [Semana de Asociaciones 2017 Milestone](https://github.com/asrob-uc3m/actas/milestone/4?closed=1) as a backup for the event.

So, uploading the pdf file directly to the https://github.com/asrob-uc3m/actas/issues/84 would be a good idea. Don't you think¿?

**Comment by jgvictores** [comment]
I would say:
1. Yes, good to upload pdf files directly to https://github.com/asrob-uc3m/actas/issues/84
1. See if there's a place for them on Google Drive too
1. Put an issue on https://github.com/asrob-uc3m/tutoriales reminding that there's material there for some nice `.md` tutorials.

**Comment by Siotma** [comment]
1. I've downloaded all the important files of this Repo. Also I have attached the source file of the presentation. I've just uploaded it to https://github.com/asrob-uc3m/actas/issues/84

2. I don't have access to the gmail Google Drive, just to the uc3m one, so I can't decide about point 2.

3. I've just put that Issue in https://github.com/asrob-uc3m/tutoriales/issues/4

**Comment by jgvictores** [comment]
1. Great!
1. Uploaded to Drive, now accessible via asrob-uc3m (gmail.com) and asrob (uc3m.es): `Charlas y talleres` > `2017 Semana de asociaciones`. Commented at https://github.com/asrob-uc3m/actas/issues/84 in case we delete this repo.
1. Perfect!

Ok to delete repo?

**Comment by Siotma** [comment]
Ok to delete

**Comment by jgvictores** [comment]
3.. 2.. 1... boom!
